#!/usr/bin/env python

"""
Frontier-ready DDP PyTorch SRCNN with lazy data pipeline.

This version avoids loading full multi-year arrays into memory.
It uses mmap-backed cached files generated by daymetread_lazy().
"""

from mpi4py import MPI
import os
import argparse
import json
from contextlib import nullcontext
from pathlib import Path

import torch
import torch.nn as nn
import torch.distributed as dist
import torch.optim as optim
from torch.utils.data import DataLoader, DistributedSampler

from srcnn_model import SRCNN
from dataread_mem_srcnn import (
    daymetread_lazy,
    SRCNNLazyDataset,
    load_scaler,
    cached_files_exist,
)


def build_parser():
    p = argparse.ArgumentParser(description="Frontier ROCm SRCNN (DDP + lazy data)")

    p.add_argument("--master_addr", type=str)
    p.add_argument("--master_port", type=str)

    p.add_argument("--base-dir", type=str, default="/lustre/orion/proj-shared/cli138/dr6/NA-Downscaling/data")
    p.add_argument("--dir-elev", type=str, default="/lustre/orion/proj-shared/cli138/dr6/NA-Downscaling/DEM")
    p.add_argument("--exp", type=str, default="SRCNN_v1")
    p.add_argument("--downscale-mode", type=str, default="0p25to0p0416",
                   choices=["1to0p25", "0p25to0p0416"])

    p.add_argument("--path-output", type=str, default=None,
                   help="Directory for cached lazy data (x_train/x_val/y_train/y_val)")
    p.add_argument("--checkpoint-dir", type=str, default=None,
                   help="Directory for checkpoints and scaler.pkl")
    p.add_argument("--prepare-data", action="store_true",
                   help="Force regeneration of cached lazy data")

    p.add_argument("--var", type=str, default="tmax_dy")
    p.add_argument("--year-start", type=int, default=1980)
    p.add_argument("--year-end", type=int, default=1981)
    p.add_argument("--scaler", type=str, default="standard", choices=["standard", "minmax"])

    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--num-workers", type=int, default=0)
    p.add_argument("--amp", action="store_true")

    return p


def is_dist():
    return dist.is_available() and dist.is_initialized()


def get_rank():
    return dist.get_rank() if is_dist() else 0


def get_world():
    return dist.get_world_size() if is_dist() else 1


def build_loader(dataset, batch_size, num_workers, is_train):
    if is_dist():
        sampler = DistributedSampler(
            dataset,
            num_replicas=get_world(),
            rank=get_rank(),
            shuffle=is_train,
            drop_last=is_train,
        )
    else:
        sampler = None

    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=(sampler is None and is_train),
        sampler=sampler,
        num_workers=num_workers,
        pin_memory=False,
    )
    return loader


def train_loop(device, args, checkpoint_dir, train_dataset, val_dataset):
    train_loader = build_loader(train_dataset, args.batch_size, args.num_workers, is_train=True)
    val_loader = build_loader(val_dataset, args.batch_size, 0, is_train=False)

    sample_x, _ = train_dataset[0]
    in_channels = int(sample_x.shape[0])

    model = SRCNN(in_channels=in_channels).to(device)

    if is_dist():
        model = nn.parallel.DistributedDataParallel(
            model,
            device_ids=[device.index],
            find_unused_parameters=False,
        )

    criterion = nn.MSELoss().to(device)
    optimizer = optim.Adam(model.parameters(), lr=5e-5)

    if args.amp:
        if device.type == "cuda":
            autocast_ctx = torch.autocast("cuda", dtype=torch.bfloat16)
        else:
            autocast_ctx = torch.autocast("cpu", dtype=torch.bfloat16)
    else:
        autocast_ctx = nullcontext()

    best_val = float("inf")
    history = {"train": [], "val": []}

    for epoch in range(args.epochs):
        if is_dist() and isinstance(train_loader.sampler, DistributedSampler):
            train_loader.sampler.set_epoch(epoch)

        model.train()
        train_loss = 0.0

        for batch_idx, (x, y) in enumerate(train_loader):
            x = x.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with autocast_ctx:
                pred = model(x)
                loss = criterion(pred, y)

            if not torch.isfinite(loss):
                raise RuntimeError(
                    f"Non-finite train loss at epoch={epoch+1}, batch={batch_idx}. "
                    f"x_finite={bool(torch.isfinite(x).all())}, "
                    f"y_finite={bool(torch.isfinite(y).all())}, "
                    f"pred_finite={bool(torch.isfinite(pred).all())}"
                )

            loss.backward()
            optimizer.step()
            train_loss += float(loss.item())

        train_loss /= max(1, len(train_loader))
        history["train"].append(train_loss)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for batch_idx, (x, y) in enumerate(val_loader):
                x = x.to(device, non_blocking=True)
                y = y.to(device, non_blocking=True)
                with autocast_ctx:
                    pred = model(x)
                    loss = criterion(pred, y)

                if not torch.isfinite(loss):
                    raise RuntimeError(
                        f"Non-finite val loss at epoch={epoch+1}, batch={batch_idx}. "
                        f"x_finite={bool(torch.isfinite(x).all())}, "
                        f"y_finite={bool(torch.isfinite(y).all())}, "
                        f"pred_finite={bool(torch.isfinite(pred).all())}"
                    )
                val_loss += float(loss.item())

        val_loss /= max(1, len(val_loader))
        history["val"].append(val_loss)

        if get_rank() == 0:
            print(f"[Epoch {epoch+1}/{args.epochs}] Train={train_loss:.6f}, Val={val_loss:.6f}", flush=True)

        if get_rank() == 0 and val_loss < best_val:
            best_val = val_loss
            torch.save(
                model.module.state_dict() if is_dist() else model.state_dict(),
                str(checkpoint_dir / "srcnn_best.pth"),
            )

    if (not is_dist()) or get_rank() == 0:
        with open(checkpoint_dir / "loss_history.json", "w") as f:
            json.dump(history, f, indent=2)



def main():
    args = build_parser().parse_args()

    comm = MPI.COMM_WORLD
    world = comm.Get_size()
    rank = comm.Get_rank()

    use_cuda = torch.cuda.is_available()
    num_gpus = torch.cuda.device_count() if use_cuda else 0
    local_rank = rank % num_gpus if (use_cuda and num_gpus > 0) else 0

    if use_cuda and num_gpus > 0:
        torch.cuda.set_device(local_rank)
        device = torch.device(f"cuda:{local_rank}")
    else:
        device = torch.device("cpu")

    os.environ["WORLD_SIZE"] = str(world)
    os.environ["RANK"] = str(rank)
    os.environ["LOCAL_RANK"] = str(local_rank)

    if world > 1:
        os.environ["MASTER_ADDR"] = str(args.master_addr)
        os.environ["MASTER_PORT"] = str(args.master_port)

        backend = "nccl" if use_cuda else "gloo"
        dist.init_process_group(
            backend=backend,
            init_method="env://",
            rank=rank,
            world_size=world,
        )
    else:
        print(f"[Rank {rank}] Single process run (no DDP). Device={device}")

    if world > 1:
        dist.barrier()

    print(
        f"[Rank {rank}] Initialized. device={device}, use_cuda={use_cuda}, "
        f"local_rank={local_rank}, world={world}",
        flush=True,
    )

    checkpoint_dir = Path(args.checkpoint_dir) if args.checkpoint_dir else Path(f"./checkpoints_{args.exp}")
    path_output = Path(args.path_output) if args.path_output else Path(f"./output/{args.exp}")

    if rank == 0:
        checkpoint_dir.mkdir(parents=True, exist_ok=True)
        path_output.mkdir(parents=True, exist_ok=True)

        must_prepare = args.prepare_data or (not cached_files_exist(path_output, checkpoint_dir))
        if must_prepare:
            print("Preparing lazy cached data...", flush=True)
            daymetread_lazy(
                path_output=path_output,
                checkpoint_dir=checkpoint_dir,
                base_dir=Path(args.base_dir),
                dir_elev=Path(args.dir_elev),
                var=args.var,
                year_start=args.year_start,
                year_end=args.year_end,
                downscale_mode=args.downscale_mode,
                scaler_type=args.scaler,
                train_fraction=0.8,
            )
        else:
            print(f"Using existing cached data under {path_output}", flush=True)

    if world > 1 and is_dist():
        dist.barrier()

    scaler = load_scaler(checkpoint_dir)
    train_dataset = SRCNNLazyDataset(path_output, scaler, split="train", use_elevation=True)
    val_dataset = SRCNNLazyDataset(path_output, scaler, split="val", use_elevation=True)

    if rank == 0:
        sx, sy = train_dataset[0]
        print(f"Train samples: {len(train_dataset)}, Val samples: {len(val_dataset)}", flush=True)
        print(f"Sample shapes: x={tuple(sx.shape)}, y={tuple(sy.shape)}", flush=True)

    train_loop(device, args, checkpoint_dir, train_dataset, val_dataset)

    if world > 1 and is_dist():
        dist.destroy_process_group()


if __name__ == "__main__":
    main()
